- name: this playbook will create the key in aws
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name:
      ec2_key:
        name: sample
        region: ap-south-1
      register: keyout
    - debug:
        var: keyout
    - name:
      copy:
        content: "{{keyout.key.private_key}}"
        dest: /root/sample11-key.pem
      when: keyout.changed == true
